# Generated by Django 3.0.4 on 2021-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
